module: CloudEnvironment
author: IBM
github_url: https://github.com/Kitura-Next/CloudEnvironment/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, CloudEnvironment.xcodeproj, -target, CloudEnvironment, LIBRARY_SEARCH_PATHS=.build/debug]
